version: '3.9'
services:
  db:
    image: mysql:8.0.31
    ports:
      - "3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --ngram_token_size=2
    healthcheck:
      test: MYSQL_PWD=${ENV_MYSQL_PASSWORD} mysql -h127.0.0.1 -P3306 -upindexer -e "quit"
    volumes:
      - /var/lib/mysql
      - ./docker/db/conf:/etc/mysql/conf.d:ro
    environment:
      - MYSQL_ROOT_PASSWORD=${ENV_MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${ENV_MYSQL_PASSWORD}
      - MYSQL_DATABASE=pindexer
      - MYSQL_USER=pindexer
  flyway:
    image: flyway/flyway:9.10.2
    command: -url=jdbc:mysql://db -schemas=pindexer -user=root -password=${ENV_MYSQL_ROOT_PASSWORD} migrate
    volumes:
      - ./docker/flyway/sql:/flyway/sql
      - ./docker/flyway/drivers:/flyway/drivers
    depends_on:
      db:
        condition: service_healthy
  web:
    image: ponkotuy/photographic-indexer:latest
    ports:
      - "8080"
    volumes:
      - ${ENV_APP_PHOTOS_DIR}:/docker/photographic-indexer/photos
    environment:
      - ENV_MYSQL_PASSWORD
      - ENV_DB_URL=jdbc:mysql://db:3306/pindexer
      - ENV_APP_EMAIL
    depends_on:
      - db
      - clip-server
  view:
    image: ponkotuy/photographic-indexer-view:latest
    ports:
      - "3000"
    depends_on:
      - web
  lb:
    image: nginx:1.23
    ports:
      - "8081:80"
    volumes:
      - ./lb/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
      - view
  flickr:
    image: ponkotuy/photographic-indexer:latest
    entrypoint: bin/flickr-crawler
    volumes:
      - ${ENV_APP_PHOTOS_DIR}:/docker/photographic-indexer/photos
    environment:
      - ENV_MYSQL_PASSWORD
      - ENV_DB_URL=jdbc:mysql://db:3306/pindexer
      - ENV_APP_EMAIL
      - ENV_FLICKR_KEY
      - ENV_FLICKR_SECRET
    depends_on:
      - db
    profiles:
      - flickr
  clip-server:
    image: ponkotuy/clip-server:latest
    ports:
      - "8000"
