name: 'Publish view docker image'
on:
  release:
    types: [published]
jobs:
  release:
    runs-on: ubuntu-latest
    environment: dockerhub
    steps:
      - uses: actions/checkout@v3
      - name: build
        working-directory: ./view/
        run: docker compose -f docker-compose.build.yml build

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: publish
        working-directory: ./view/
        run: |
          docker tag ponkotuy/photographic-indexer-view:latest ponkotuy/photographic-indexer-view:${GITHUB_REF##*/}
          docker push ponkotuy/photographic-indexer-view:${GITHUB_REF##*/}
          docker push ponkotuy/photographic-indexer-view:latest
